sudo: required
dist: trusty
cache:
  directories:
    - node_modules
language: node_js
node_js:
  - "6"

addons:
  apt_packages:
    - pandoc
    - texlive-full
    - inkscape

before_install:
  - rvm install ruby-2.2.0
  - rvm --default use 2.2.0
  - gem install bundler
  - rvm . do bundle install

install:
  - npm install firebase-tools -g
  - npm install

script:
  - ./shellscripts/build-book.sh
  - if [[ "$TRAVIS_BRANCH" = "master" && "$TRAVIS_OS_NAME" = "linux" && "$TRAVIS_PULL_REQUEST" = "false" ]]; then firebase deploy --token "$FIREBASE_TOKEN" --project default --non-interactive; fi
