sudo: required
dist: trusty

language: node_js
node_js:
  - "6"

addons:
  apt_packages:
    - pandoc
    - texlive-full
    - inkscape

before_install:
- npm install firebase-tools -g
- npm install

script:
  - ./shellscripts/build-book.sh
  - if [[ "$TRAVIS_BRANCH" = "master" && "$TRAVIS_OS_NAME" = "linux" && "$TRAVIS_PULL_REQUEST" = "false" ]]; then firebase deploy --token "$FIREBASE_TOKEN" --project default --non-interactive; fi
