source: ./build
destination: ./build/_site/
layouts_dir: ./jekyll/_layouts/
includes_dir: ./jekyll/_includes/
live_domain: https://web-push-book.gauntface.com

exclude:
  - _content/chapter-01/00-info.md
  - _content/epub-metadata.yaml

defaults:
  -
    scope:
      path: ""
    values:
      layout: "book-page"

collections:
  content:
    output: true
    permalink: /:path/

gems:
  - jekyll-sitemap
