source: .
layouts_dir: ./jekyll/_layouts/
includes_dir: ./jekyll/_includes/

exclude:
  - README.md
  - WRITING.md
  - firebase.json
  - database.rules.json
  - Gemfile*
  - LICENSE
  - package.json
  - test/
  - third_party/
  - node_modules/
  - shellscripts/

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
