
name: Build and Test

on: push

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    # Get the code
    - uses: actions/checkout@v2

    # Install dependencies
    - name: Install Go
      uses: actions/setup-go@v3
      with:
        go-version: '^1.13.1'
    - name: Install Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.74.3'
    - name: Install go-html-asset-manager
      run: |
        go get -u github.com/gauntface/go-html-asset-manager/cmds/htmlassets/
        go get -u github.com/gauntface/go-html-asset-manager/cmds/genimgs/
    - name: Install NPM Deps
      run: npm install

    # Build it
    - name: Build
      run: npm run build